version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: encanto-ticket-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helpdesk

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: encanto-ticket-backend

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: encanto-ticket-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

volumes:
  postgres_data: